Repository vopo-team/contact-management-assistant, pull requests merged in 2025-07, with the labels that each got.

#2 build!: init project
  .env.example
  .gitignore
  CONTRIBUTING.md
  README.md
  SECURITY.md
  commands/__init__.py
  main.py
  models/__init__.py
  requirements.txt
  utils/__init__.py
Labels: enhancement, good first issue

#14 feat!: add field class #4
  models/field.py
Labels: enhancement

#24 feat: integrate colorama. closes #23
  requirements.txt
Labels: integration

#22 feat: add command class.
  commands/command.py
Labels: class, structure

#30 feat: create Note class
  models/note.py
Labels: class

#34 feat: add disptacher class
  commands/command.py
  commands/dispatcher.py
Labels: class, structure

#48 feat: create template for Record
  models/record.py
Labels: enhancement, class

#52 29 command parser - done
  utils/command_parser.py
Labels: class, utility

#54 feat: extend Record functionality by adding phone CRUD
  models/record.py
Labels: enhancement, class

#59 dev: create dummy start of application
  commands/dispatcher.py
  main.py
Labels: enhancement, structure

#64 dev: finish record
  models/note.py
  models/record.py
  requirements.txt
Labels: enhancement, class

#74 chore: integrate tabulate
  README.md
  requirements.txt
Labels: integration

#80 fix: handle case with two similar names
  commands/add.py
  commands/change.py
  commands/delete.py
  commands/find.py
  commands/find_notes.py
  commands/help.py
  models/contact_book.py
  models/record.py
Labels: enhancement, invalid

#83 chore: update structure and make our bot as a package
  .gitignore
  README.md
  docs/CONTRIBUTING.md
  docs/SECURITY.md
  pyproject.toml
  requirements.txt
  src/commands/__init__.py
  src/commands/add.py
  src/commands/birthdays.py
  src/commands/change.py
  src/commands/close.py
  src/commands/command.py
  src/commands/delete.py
  src/commands/dispatcher.py
  src/commands/find.py
  src/commands/find_notes.py
  src/commands/hello.py
  src/commands/help.py
  src/commands/invalid.py
  src/main.py
  src/models/__init__.py
  src/models/address.py
  src/models/birthday.py
  src/models/contact_book.py
  src/models/email.py
  src/models/field.py
  src/models/name.py
  src/models/note.py
  src/models/phone.py
  src/models/record.py
  src/models/tag.py
  src/utils/__init__.py
  src/utils/color_message.py
  src/utils/command_parser.py
  src/utils/format_message.py
  src/utils/fuzz_comparator.py
  src/utils/input_normalizer.py
  src/utils/pickle_reader.py
Labels: documentation, enhancement, structure
